name: Reusable Clone Repository

on:
  workflow_call:  # Makes this workflow reusable
    inputs:
      repo_url:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  clone-repo:
    name: Clone Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        run: |
          echo "Cloning repository from ${{ inputs.repo_url }} branch ${{ inputs.branch }}"
          git clone --branch ${{ inputs.branch }} ${{ inputs.repo_url }} cloned-repo

      - name: List Cloned Repository Files
        run: ls -la cloned-repo
